In [1]:
from transformers import TFBertModel, BertTokenizer

In [6]:
import tensorflow as tf

In [23]:
tokenizer = BertTokenizer.from_pretrained("bert-base-cased")

In [24]:
model = TFBertModel.from_pretrained("bert-base-cased")

In [46]:
input_ids = tf.convert_to_tensor([tokenizer.encode("Here is some text to encode. \n It doesn't really make sense by itself.", add_special_tokens=True)])
last_hidden_states = model(input_ids)[0]

In [45]:
input_ids

<tf.Tensor: shape=(1, 18), dtype=int32, numpy=
array([[ 3446,  1110,  1199,  3087,  1106,  4035, 13775,   119,  1135,
         2144,   112,   189,  1541,  1294,  2305,  1118,  2111,   119]],
      dtype=int32)>

In [47]:
input_ids

<tf.Tensor: shape=(1, 20), dtype=int32, numpy=
array([[  101,  3446,  1110,  1199,  3087,  1106,  4035, 13775,   119,
         1135,  2144,   112,   189,  1541,  1294,  2305,  1118,  2111,
          119,   102]], dtype=int32)>

In [43]:
tokenizer.tokenize("Here is some text to encode. It doesn't really make sense by itself.")

['Here',
 'is',
 'some',
 'text',
 'to',
 'en',
 '##code',
 '.',
 'It',
 'doesn',
 "'",
 't',
 'really',
 'make',
 'sense',
 'by',
 'itself',
 '.']

In [16]:
res = tf.reduce_mean(last_hidden_states, axis = 1)

In [19]:
res_np = res.numpy()[0]
res_np.shape

(768,)

In [20]:
final_res = []
for elem in res_np:
    final_res.append(float(elem))

In [22]:
final_res[0].dtype

AttributeError: 'float' object has no attribute 'dtype'